<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Middle East & North Africa
            ['name_ar' => 'لبنان', 'name_en' => 'Lebanon'],
            ['name_ar' => 'الإمارات العربية المتحدة', 'name_en' => 'United Arab Emirates'],
            ['name_ar' => 'المملكة العربية السعودية', 'name_en' => 'Saudi Arabia'],
            ['name_ar' => 'مصر', 'name_en' => 'Egypt'],
            ['name_ar' => 'الأردن', 'name_en' => 'Jordan'],
            ['name_ar' => 'العراق', 'name_en' => 'Iraq'],
            ['name_ar' => 'سوريا', 'name_en' => 'Syria'],
            ['name_ar' => 'الكويت', 'name_en' => 'Kuwait'],
            ['name_ar' => 'البحرين', 'name_en' => 'Bahrain'],
            ['name_ar' => 'قطر', 'name_en' => 'Qatar'],
            ['name_ar' => 'عمان', 'name_en' => 'Oman'],
            ['name_ar' => 'اليمن', 'name_en' => 'Yemen'],
            ['name_ar' => 'فلسطين', 'name_en' => 'Palestine'],
            ['name_ar' => 'ليبيا', 'name_en' => 'Libya'],
            ['name_ar' => 'تونس', 'name_en' => 'Tunisia'],
            ['name_ar' => 'الجزائر', 'name_en' => 'Algeria'],
            ['name_ar' => 'المغرب', 'name_en' => 'Morocco'],
            ['name_ar' => 'السودان', 'name_en' => 'Sudan'],
            ['name_ar' => 'موريتانيا', 'name_en' => 'Mauritania'],
            ['name_ar' => 'الصومال', 'name_en' => 'Somalia'],
            ['name_ar' => 'جيبوتي', 'name_en' => 'Djibouti'],
            ['name_ar' => 'جزر القمر', 'name_en' => 'Comoros'],

            // Europe
            ['name_ar' => 'المملكة المتحدة', 'name_en' => 'United Kingdom'],
            ['name_ar' => 'فرنسا', 'name_en' => 'France'],
            ['name_ar' => 'ألمانيا', 'name_en' => 'Germany'],
            ['name_ar' => 'إيطاليا', 'name_en' => 'Italy'],
            ['name_ar' => 'إسبانيا', 'name_en' => 'Spain'],
            ['name_ar' => 'البرتغال', 'name_en' => 'Portugal'],
            ['name_ar' => 'هولندا', 'name_en' => 'Netherlands'],
            ['name_ar' => 'بلجيكا', 'name_en' => 'Belgium'],
            ['name_ar' => 'سويسرا', 'name_en' => 'Switzerland'],
            ['name_ar' => 'النمسا', 'name_en' => 'Austria'],
            ['name_ar' => 'اليونان', 'name_en' => 'Greece'],
            ['name_ar' => 'السويد', 'name_en' => 'Sweden'],
            ['name_ar' => 'النرويج', 'name_en' => 'Norway'],
            ['name_ar' => 'الدنمارك', 'name_en' => 'Denmark'],
            ['name_ar' => 'فنلندا', 'name_en' => 'Finland'],
            ['name_ar' => 'آيسلندا', 'name_en' => 'Iceland'],
            ['name_ar' => 'أيرلندا', 'name_en' => 'Ireland'],
            ['name_ar' => 'بولندا', 'name_en' => 'Poland'],
            ['name_ar' => 'التشيك', 'name_en' => 'Czech Republic'],
            ['name_ar' => 'المجر', 'name_en' => 'Hungary'],
            ['name_ar' => 'رومانيا', 'name_en' => 'Romania'],
            ['name_ar' => 'بلغاريا', 'name_en' => 'Bulgaria'],
            ['name_ar' => 'كرواتيا', 'name_en' => 'Croatia'],
            ['name_ar' => 'صربيا', 'name_en' => 'Serbia'],
            ['name_ar' => 'سلوفينيا', 'name_en' => 'Slovenia'],
            ['name_ar' => 'سلوفاكيا', 'name_en' => 'Slovakia'],
            ['name_ar' => 'أوكرانيا', 'name_en' => 'Ukraine'],
            ['name_ar' => 'روسيا', 'name_en' => 'Russia'],
            ['name_ar' => 'بيلاروسيا', 'name_en' => 'Belarus'],
            ['name_ar' => 'مولدوفا', 'name_en' => 'Moldova'],
            ['name_ar' => 'إستونيا', 'name_en' => 'Estonia'],
            ['name_ar' => 'لاتفيا', 'name_en' => 'Latvia'],
            ['name_ar' => 'ليتوانيا', 'name_en' => 'Lithuania'],
            ['name_ar' => 'ألبانيا', 'name_en' => 'Albania'],
            ['name_ar' => 'مقدونيا الشمالية', 'name_en' => 'North Macedonia'],
            ['name_ar' => 'البوسنة والهرسك', 'name_en' => 'Bosnia and Herzegovina'],
            ['name_ar' => 'الجبل الأسود', 'name_en' => 'Montenegro'],
            ['name_ar' => 'كوسوفو', 'name_en' => 'Kosovo'],
            ['name_ar' => 'لوكسمبورغ', 'name_en' => 'Luxembourg'],
            ['name_ar' => 'مالطا', 'name_en' => 'Malta'],
            ['name_ar' => 'قبرص', 'name_en' => 'Cyprus'],

            // Asia
            ['name_ar' => 'الصين', 'name_en' => 'China'],
            ['name_ar' => 'اليابان', 'name_en' => 'Japan'],
            ['name_ar' => 'كوريا الجنوبية', 'name_en' => 'South Korea'],
            ['name_ar' => 'كوريا الشمالية', 'name_en' => 'North Korea'],
            ['name_ar' => 'الهند', 'name_en' => 'India'],
            ['name_ar' => 'باكستان', 'name_en' => 'Pakistan'],
            ['name_ar' => 'بنغلاديش', 'name_en' => 'Bangladesh'],
            ['name_ar' => 'أفغانستان', 'name_en' => 'Afghanistan'],
            ['name_ar' => 'إيران', 'name_en' => 'Iran'],
            ['name_ar' => 'تركيا', 'name_en' => 'Turkey'],
            ['name_ar' => 'أذربيجان', 'name_en' => 'Azerbaijan'],
            ['name_ar' => 'أرمينيا', 'name_en' => 'Armenia'],
            ['name_ar' => 'جورجيا', 'name_en' => 'Georgia'],
            ['name_ar' => 'كازاخستان', 'name_en' => 'Kazakhstan'],
            ['name_ar' => 'أوزبكستان', 'name_en' => 'Uzbekistan'],
            ['name_ar' => 'تركمانستان', 'name_en' => 'Turkmenistan'],
            ['name_ar' => 'طاجيكستان', 'name_en' => 'Tajikistan'],
            ['name_ar' => 'قيرغيزستان', 'name_en' => 'Kyrgyzstan'],
            ['name_ar' => 'تايلاند', 'name_en' => 'Thailand'],
            ['name_ar' => 'فيتنام', 'name_en' => 'Vietnam'],
            ['name_ar' => 'إندونيسيا', 'name_en' => 'Indonesia'],
            ['name_ar' => 'ماليزيا', 'name_en' => 'Malaysia'],
            ['name_ar' => 'سنغافورة', 'name_en' => 'Singapore'],
            ['name_ar' => 'الفلبين', 'name_en' => 'Philippines'],
            ['name_ar' => 'بروناي', 'name_en' => 'Brunei'],
            ['name_ar' => 'ميانمار', 'name_en' => 'Myanmar'],
            ['name_ar' => 'لاوس', 'name_en' => 'Laos'],
            ['name_ar' => 'كمبوديا', 'name_en' => 'Cambodia'],
            ['name_ar' => 'نيبال', 'name_en' => 'Nepal'],
            ['name_ar' => 'بوتان', 'name_en' => 'Bhutan'],
            ['name_ar' => 'سريلانكا', 'name_en' => 'Sri Lanka'],
            ['name_ar' => 'جزر المالديف', 'name_en' => 'Maldives'],
            ['name_ar' => 'منغوليا', 'name_en' => 'Mongolia'],
            ['name_ar' => 'تيمور الشرقية', 'name_en' => 'East Timor'],

            // Americas
            ['name_ar' => 'الولايات المتحدة', 'name_en' => 'United States'],
            ['name_ar' => 'كندا', 'name_en' => 'Canada'],
            ['name_ar' => 'المكسيك', 'name_en' => 'Mexico'],
            ['name_ar' => 'البرازيل', 'name_en' => 'Brazil'],
            ['name_ar' => 'الأرجنتين', 'name_en' => 'Argentina'],
            ['name_ar' => 'تشيلي', 'name_en' => 'Chile'],
            ['name_ar' => 'كولومبيا', 'name_en' => 'Colombia'],
            ['name_ar' => 'فنزويلا', 'name_en' => 'Venezuela'],
            ['name_ar' => 'بيرو', 'name_en' => 'Peru'],
            ['name_ar' => 'الإكوادور', 'name_en' => 'Ecuador'],
            ['name_ar' => 'بوليفيا', 'name_en' => 'Bolivia'],
            ['name_ar' => 'باراغواي', 'name_en' => 'Paraguay'],
            ['name_ar' => 'أوروغواي', 'name_en' => 'Uruguay'],
            ['name_ar' => 'غيانا', 'name_en' => 'Guyana'],
            ['name_ar' => 'سورينام', 'name_en' => 'Suriname'],
            ['name_ar' => 'غويانا الفرنسية', 'name_en' => 'French Guiana'],
            ['name_ar' => 'كوبا', 'name_en' => 'Cuba'],
            ['name_ar' => 'جامايكا', 'name_en' => 'Jamaica'],
            ['name_ar' => 'هايتي', 'name_en' => 'Haiti'],
            ['name_ar' => 'جمهورية الدومينيكان', 'name_en' => 'Dominican Republic'],
            ['name_ar' => 'بورتوريكو', 'name_en' => 'Puerto Rico'],
            ['name_ar' => 'كوستاريكا', 'name_en' => 'Costa Rica'],
            ['name_ar' => 'بنما', 'name_en' => 'Panama'],
            ['name_ar' => 'غواتيمالا', 'name_en' => 'Guatemala'],
            ['name_ar' => 'هندوراس', 'name_en' => 'Honduras'],
            ['name_ar' => 'نيكاراغوا', 'name_en' => 'Nicaragua'],
            ['name_ar' => 'السلفادور', 'name_en' => 'El Salvador'],
            ['name_ar' => 'بليز', 'name_en' => 'Belize'],
            ['name_ar' => 'ترينيداد وتوباغو', 'name_en' => 'Trinidad and Tobago'],
            ['name_ar' => 'باربادوس', 'name_en' => 'Barbados'],
            ['name_ar' => 'باهاماس', 'name_en' => 'Bahamas'],

            // Africa
            ['name_ar' => 'نيجيريا', 'name_en' => 'Nigeria'],
            ['name_ar' => 'إثيوبيا', 'name_en' => 'Ethiopia'],
            ['name_ar' => 'جنوب أفريقيا', 'name_en' => 'South Africa'],
            ['name_ar' => 'كينيا', 'name_en' => 'Kenya'],
            ['name_ar' => 'تنزانيا', 'name_en' => 'Tanzania'],
            ['name_ar' => 'أوغندا', 'name_en' => 'Uganda'],
            ['name_ar' => 'غانا', 'name_en' => 'Ghana'],
            ['name_ar' => 'الكاميرون', 'name_en' => 'Cameroon'],
            ['name_ar' => 'كوت ديفوار', 'name_en' => 'Ivory Coast'],
            ['name_ar' => 'أنغولا', 'name_en' => 'Angola'],
            ['name_ar' => 'موزمبيق', 'name_en' => 'Mozambique'],
            ['name_ar' => 'مدغشقر', 'name_en' => 'Madagascar'],
            ['name_ar' => 'زامبيا', 'name_en' => 'Zambia'],
            ['name_ar' => 'زيمبابوي', 'name_en' => 'Zimbabwe'],
            ['name_ar' => 'مالي', 'name_en' => 'Mali'],
            ['name_ar' => 'بوركينا فاسو', 'name_en' => 'Burkina Faso'],
            ['name_ar' => 'النيجر', 'name_en' => 'Niger'],
            ['name_ar' => 'تشاد', 'name_en' => 'Chad'],
            ['name_ar' => 'السنغال', 'name_en' => 'Senegal'],
            ['name_ar' => 'غينيا', 'name_en' => 'Guinea'],
            ['name_ar' => 'رواندا', 'name_en' => 'Rwanda'],
            ['name_ar' => 'بوروندي', 'name_en' => 'Burundi'],
            ['name_ar' => 'بنين', 'name_en' => 'Benin'],
            ['name_ar' => 'توغو', 'name_en' => 'Togo'],
            ['name_ar' => 'سيراليون', 'name_en' => 'Sierra Leone'],
            ['name_ar' => 'ليبيريا', 'name_en' => 'Liberia'],
            ['name_ar' => 'جمهورية أفريقيا الوسطى', 'name_en' => 'Central African Republic'],
            ['name_ar' => 'الكونغو', 'name_en' => 'Republic of the Congo'],
            ['name_ar' => 'جمهورية الكونغو الديمقراطية', 'name_en' => 'Democratic Republic of the Congo'],
            ['name_ar' => 'الغابون', 'name_en' => 'Gabon'],
            ['name_ar' => 'غينيا الاستوائية', 'name_en' => 'Equatorial Guinea'],
            ['name_ar' => 'بوتسوانا', 'name_en' => 'Botswana'],
            ['name_ar' => 'ناميبيا', 'name_en' => 'Namibia'],
            ['name_ar' => 'موريشيوس', 'name_en' => 'Mauritius'],
            ['name_ar' => 'سيشل', 'name_en' => 'Seychelles'],
            ['name_ar' => 'إريتريا', 'name_en' => 'Eritrea'],
            ['name_ar' => 'جنوب السودان', 'name_en' => 'South Sudan'],
            ['name_ar' => 'ملاوي', 'name_en' => 'Malawi'],
            ['name_ar' => 'ليسوتو', 'name_en' => 'Lesotho'],
            ['name_ar' => 'إسواتيني', 'name_en' => 'Eswatini'],
            ['name_ar' => 'غامبيا', 'name_en' => 'Gambia'],
            ['name_ar' => 'غينيا بيساو', 'name_en' => 'Guinea-Bissau'],
            ['name_ar' => 'الرأس الأخضر', 'name_en' => 'Cape Verde'],
            ['name_ar' => 'ساو تومي وبرينسيب', 'name_en' => 'Sao Tome and Principe'],

            // Oceania
            ['name_ar' => 'أستراليا', 'name_en' => 'Australia'],
            ['name_ar' => 'نيوزيلندا', 'name_en' => 'New Zealand'],
            ['name_ar' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea'],
            ['name_ar' => 'فيجي', 'name_en' => 'Fiji'],
            ['name_ar' => 'جزر سليمان', 'name_en' => 'Solomon Islands'],
            ['name_ar' => 'ساموا', 'name_en' => 'Samoa'],
            ['name_ar' => 'فانواتو', 'name_en' => 'Vanuatu'],
            ['name_ar' => 'تونغا', 'name_en' => 'Tonga'],
            ['name_ar' => 'كيريباتي', 'name_en' => 'Kiribati'],
            ['name_ar' => 'ميكرونيزيا', 'name_en' => 'Micronesia'],
            ['name_ar' => 'جزر مارشال', 'name_en' => 'Marshall Islands'],
            ['name_ar' => 'بالاو', 'name_en' => 'Palau'],
            ['name_ar' => 'ناورو', 'name_en' => 'Nauru'],
            ['name_ar' => 'توفالو', 'name_en' => 'Tuvalu'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
