<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Town;
use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // List of duplicate town names that need district suffix
        $duplicateTowns = [
            'عميق', 'البيره', 'بكيفا', 'عين عرب', 'كوكبا',
            'الخلوات', 'علمان', 'الخريبه', 'بسابا', 'عين الرمانة',
        ];

        $towns = [
            ['name' => 'الخياره', 'district' => 'البقاع الغربي'],
            ['name' => 'الدكوه', 'district' => 'البقاع الغربي'],
            ['name' => 'الروضة', 'district' => 'البقاع الغربي'],
            ['name' => 'السلطان يعقوب التحتا', 'district' => 'البقاع الغربي'],
            ['name' => 'السلطان يعقوب الفوقا', 'district' => 'البقاع الغربي'],
            ['name' => 'الشبرقية', 'district' => 'البقاع الغربي'],
            ['name' => 'الصويري', 'district' => 'البقاع الغربي'],
            ['name' => 'القرعون', 'district' => 'البقاع الغربي'],
            ['name' => 'المرج', 'district' => 'البقاع الغربي'],
            ['name' => 'المنارة', 'district' => 'البقاع الغربي'],
            ['name' => 'المنصوره', 'district' => 'البقاع الغربي'],
            ['name' => 'باب مارع', 'district' => 'البقاع الغربي'],
            ['name' => 'بعلول', 'district' => 'البقاع الغربي'],
            ['name' => 'تل ذنوب', 'district' => 'البقاع الغربي'],
            ['name' => 'جب جنين', 'district' => 'البقاع الغربي'],
            ['name' => 'حوش الحريمه', 'district' => 'البقاع الغربي'],
            ['name' => 'خربة قنافار', 'district' => 'البقاع الغربي'],
            ['name' => 'زلايا', 'district' => 'البقاع الغربي'],
            ['name' => 'سحمر', 'district' => 'البقاع الغربي'],
            ['name' => 'صغبين', 'district' => 'البقاع الغربي'],
            ['name' => 'عانا', 'district' => 'البقاع الغربي'],
            ['name' => 'عميق', 'district' => 'البقاع الغربي'],
            ['name' => 'عيتيت', 'district' => 'البقاع الغربي'],
            ['name' => 'عين التينه', 'district' => 'البقاع الغربي'],
            ['name' => 'عين زبده', 'district' => 'البقاع الغربي'],
            ['name' => 'غزه', 'district' => 'البقاع الغربي'],
            ['name' => 'قليا', 'district' => 'البقاع الغربي'],
            ['name' => 'كامد اللوز', 'district' => 'البقاع الغربي'],
            ['name' => 'كفريا', 'district' => 'البقاع الغربي'],
            ['name' => 'لالا', 'district' => 'البقاع الغربي'],
            ['name' => 'لبايا', 'district' => 'البقاع الغربي'],
            ['name' => 'لوسيا', 'district' => 'البقاع الغربي'],
            ['name' => 'مشغره التحتا', 'district' => 'البقاع الغربي'],
            ['name' => 'مشغره الفوقا', 'district' => 'البقاع الغربي'],
            ['name' => 'ميدون', 'district' => 'البقاع الغربي'],
            ['name' => 'يحمر', 'district' => 'البقاع الغربي'],
            ['name' => 'البيره', 'district' => 'راشيا'],
            ['name' => 'الحوش', 'district' => 'راشيا'],
            ['name' => 'الرفيد', 'district' => 'راشيا'],
            ['name' => 'العقبة', 'district' => 'راشيا'],
            ['name' => 'بكا', 'district' => 'راشيا'],
            ['name' => 'بكيفا', 'district' => 'راشيا'],
            ['name' => 'بيت لهيا', 'district' => 'راشيا'],
            ['name' => 'تنوره', 'district' => 'راشيا'],
            ['name' => 'حلوه', 'district' => 'راشيا'],
            ['name' => 'خربة روحا', 'district' => 'راشيا'],
            ['name' => 'دير العشائر', 'district' => 'راشيا'],
            ['name' => 'راشيا حي الفوقا', 'district' => 'راشيا'],
            ['name' => 'راشيا حي الكواسبه', 'district' => 'راشيا'],
            ['name' => 'راشيا حي الميدان', 'district' => 'راشيا'],
            ['name' => 'سلساتا', 'district' => 'راشيا'],
            ['name' => 'ضهر الاحمر', 'district' => 'راشيا'],
            ['name' => 'عيتا الفخار', 'district' => 'راشيا'],
            ['name' => 'عيحا', 'district' => 'راشيا'],
            ['name' => 'عين حرشا', 'district' => 'راشيا'],
            ['name' => 'عين عرب', 'district' => 'راشيا'],
            ['name' => 'عين عطا', 'district' => 'راشيا'],
            ['name' => 'كفردنيس', 'district' => 'راشيا'],
            ['name' => 'كفرقوق', 'district' => 'راشيا'],
            ['name' => 'كفرمشكي', 'district' => 'راشيا'],
            ['name' => 'كوكبا', 'district' => 'راشيا'],
            ['name' => 'مجدل بلهيص', 'district' => 'راشيا'],
            ['name' => 'محيدثه', 'district' => 'راشيا'],
            ['name' => 'مدوخا', 'district' => 'راشيا'],
            ['name' => 'ينطا', 'district' => 'راشيا'],
            ['name' => 'ابو قمحه', 'district' => 'حاصبيا'],
            ['name' => 'الخلوات', 'district' => 'حاصبيا'],
            ['name' => 'الدلافة', 'district' => 'حاصبيا'],
            ['name' => 'الفرديس', 'district' => 'حاصبيا'],
            ['name' => 'الكفير', 'district' => 'حاصبيا'],
            ['name' => 'الماري', 'district' => 'حاصبيا'],
            ['name' => 'المجيديه', 'district' => 'حاصبيا'],
            ['name' => 'الهبارية', 'district' => 'حاصبيا'],
            ['name' => 'برغز', 'district' => 'حاصبيا'],
            ['name' => 'حاصبيا حي السراي', 'district' => 'حاصبيا'],
            ['name' => 'حاصبيا حي العين', 'district' => 'حاصبيا'],
            ['name' => 'حاصبيا حي الفوقاني', 'district' => 'حاصبيا'],
            ['name' => 'حاصبيا حي صفيفة', 'district' => 'حاصبيا'],
            ['name' => 'راشيا الفخار', 'district' => 'حاصبيا'],
            ['name' => 'شبعا شرقي', 'district' => 'حاصبيا'],
            ['name' => 'شبعا غربي', 'district' => 'حاصبيا'],
            ['name' => 'شويا', 'district' => 'حاصبيا'],
            ['name' => 'عين جرفا', 'district' => 'حاصبيا'],
            ['name' => 'عين قنيا', 'district' => 'حاصبيا'],
            ['name' => 'كفر حمام', 'district' => 'حاصبيا'],
            ['name' => 'كفرشوبا', 'district' => 'حاصبيا'],
            ['name' => 'كوكبا', 'district' => 'حاصبيا'],
            ['name' => 'مرج الزهور', 'district' => 'حاصبيا'],
            ['name' => 'ميمس', 'district' => 'حاصبيا'],
            ['name' => 'ابل السقي', 'district' => 'مرجعيون'],
            ['name' => 'الجديدة حي السراي', 'district' => 'مرجعيون'],
            ['name' => 'الجديدة حي العيون', 'district' => 'مرجعيون'],
            ['name' => 'الجديدة حي القلعة', 'district' => 'مرجعيون'],
            ['name' => 'الجديدة حي المدارس', 'district' => 'مرجعيون'],
            ['name' => 'الخيام جنوبي', 'district' => 'مرجعيون'],
            ['name' => 'الخيام شرقي', 'district' => 'مرجعيون'],
            ['name' => 'الخيام شمالي', 'district' => 'مرجعيون'],
            ['name' => 'الخيام غربي', 'district' => 'مرجعيون'],
            ['name' => 'الطيبه', 'district' => 'مرجعيون'],
            ['name' => 'القصير', 'district' => 'مرجعيون'],
            ['name' => 'القليعه', 'district' => 'مرجعيون'],
            ['name' => 'الوزاني', 'district' => 'مرجعيون'],
            ['name' => 'برج الملوك', 'district' => 'مرجعيون'],
            ['name' => 'بلاط', 'district' => 'مرجعيون'],
            ['name' => 'بليدا', 'district' => 'مرجعيون'],
            ['name' => 'بني حيان', 'district' => 'مرجعيون'],
            ['name' => 'بويضة', 'district' => 'مرجعيون'],
            ['name' => 'تولين', 'district' => 'مرجعيون'],
            ['name' => 'حولا', 'district' => 'مرجعيون'],
            ['name' => 'دبين', 'district' => 'مرجعيون'],
            ['name' => 'دير سريان', 'district' => 'مرجعيون'],
            ['name' => 'دير ميماس', 'district' => 'مرجعيون'],
            ['name' => 'رب ثلاثين', 'district' => 'مرجعيون'],
            ['name' => 'سرده والعمره', 'district' => 'مرجعيون'],
            ['name' => 'صوانه', 'district' => 'مرجعيون'],
            ['name' => 'طلوسه', 'district' => 'مرجعيون'],
            ['name' => 'عدشيت', 'district' => 'مرجعيون'],
            ['name' => 'عديسه', 'district' => 'مرجعيون'],
            ['name' => 'علمان', 'district' => 'مرجعيون'],
            ['name' => 'عين عرب', 'district' => 'مرجعيون'],
            ['name' => 'قبريخا', 'district' => 'مرجعيون'],
            ['name' => 'قنطره', 'district' => 'مرجعيون'],
            ['name' => 'كفركلا', 'district' => 'مرجعيون'],
            ['name' => 'مجدل سلم', 'district' => 'مرجعيون'],
            ['name' => 'محيبيب', 'district' => 'مرجعيون'],
            ['name' => 'مركبا', 'district' => 'مرجعيون'],
            ['name' => 'ميس الجبل جنوبي', 'district' => 'مرجعيون'],
            ['name' => 'ميس الجبل شرقي', 'district' => 'مرجعيون'],
            ['name' => 'ميس الجبل شمالي', 'district' => 'مرجعيون'],
            ['name' => 'ميس الجبل غربي', 'district' => 'مرجعيون'],
            ['name' => 'الباشورة', 'district' => 'بيروت 2'],
            ['name' => 'المرفأ', 'district' => 'بيروت 2'],
            ['name' => 'المزرعة', 'district' => 'بيروت 2'],
            ['name' => 'المصيطبة', 'district' => 'بيروت 2'],
            ['name' => 'دار المريسة', 'district' => 'بيروت 2'],
            ['name' => 'رأس بيروت', 'district' => 'بيروت 2'],
            ['name' => 'زقاق البلاط', 'district' => 'بيروت 2'],
            ['name' => 'ميناء الحصن', 'district' => 'بيروت 2'],
            ['name' => 'ارصون', 'district' => 'بعبدا'],
            ['name' => 'الحازميه', 'district' => 'بعبدا'],
            ['name' => 'الحدث شمالي', 'district' => 'بعبدا'],
            ['name' => 'الحدث قبلي', 'district' => 'بعبدا'],
            ['name' => 'الخريبه', 'district' => 'بعبدا'],
            ['name' => 'الخلوات', 'district' => 'بعبدا'],
            ['name' => 'الدليبه', 'district' => 'بعبدا'],
            ['name' => 'الشبانيه', 'district' => 'بعبدا'],
            ['name' => 'الشياح بئر العبد', 'district' => 'بعبدا'],
            ['name' => 'الشياح حي الكنيسة', 'district' => 'بعبدا'],
            ['name' => 'الشياح حي كرم الزيتون', 'district' => 'بعبدا'],
            ['name' => 'العباديه', 'district' => 'بعبدا'],
            ['name' => 'العربانية', 'district' => 'بعبدا'],
            ['name' => 'الغبيري بئر حسن', 'district' => 'بعبدا'],
            ['name' => 'الغبيري حي الجامع', 'district' => 'بعبدا'],
            ['name' => 'الفياضية', 'district' => 'بعبدا'],
            ['name' => 'القريه', 'district' => 'بعبدا'],
            ['name' => 'القصيبه', 'district' => 'بعبدا'],
            ['name' => 'القلعه', 'district' => 'بعبدا'],
            ['name' => 'الكنيسه', 'district' => 'بعبدا'],
            ['name' => 'اللويزه', 'district' => 'بعبدا'],
            ['name' => 'الليلكه', 'district' => 'بعبدا'],
            ['name' => 'المرداشة', 'district' => 'بعبدا'],
            ['name' => 'المريجه', 'district' => 'بعبدا'],
            ['name' => 'الهلالية', 'district' => 'بعبدا'],
            ['name' => 'بتبيات', 'district' => 'بعبدا'],
            ['name' => 'بتخنيه', 'district' => 'بعبدا'],
            ['name' => 'برج البراجنة حي السنديان', 'district' => 'بعبدا'],
            ['name' => 'برج البراجنة حي السياد', 'district' => 'بعبدا'],
            ['name' => 'برج البراجنة حي المنشية', 'district' => 'بعبدا'],
            ['name' => 'بزبدين', 'district' => 'بعبدا'],
            ['name' => 'بسابا', 'district' => 'بعبدا'],
            ['name' => 'بطشيه', 'district' => 'بعبدا'],
            ['name' => 'بعبدا', 'district' => 'بعبدا'],
            ['name' => 'بعلشميه', 'district' => 'بعبدا'],
            ['name' => 'بمريم', 'district' => 'بعبدا'],
            ['name' => 'تحويطة الغدير', 'district' => 'بعبدا'],
            ['name' => 'تحويطة النهر', 'district' => 'بعبدا'],
            ['name' => 'ترشيش', 'district' => 'بعبدا'],
            ['name' => 'جوار الحوز', 'district' => 'بعبدا'],
            ['name' => 'جورة ارصون', 'district' => 'بعبدا'],
            ['name' => 'حارة البطم', 'district' => 'بعبدا'],
            ['name' => 'حارة الست', 'district' => 'بعبدا'],
            ['name' => 'حارة حريك حي الرويس', 'district' => 'بعبدا'],
            ['name' => 'حارة حريك حي الكنيسة', 'district' => 'بعبدا'],
            ['name' => 'حارة حريك قرانوح', 'district' => 'بعبدا'],
            ['name' => 'حارة حمزه', 'district' => 'بعبدا'],
            ['name' => 'حاصبيا المتن', 'district' => 'بعبدا'],
            ['name' => 'حمانا', 'district' => 'بعبدا'],
            ['name' => 'دير الحرف', 'district' => 'بعبدا'],
            ['name' => 'دير خونا', 'district' => 'بعبدا'],
            ['name' => 'دير مار الياس الكحلونية', 'district' => 'بعبدا'],
            ['name' => 'راس الحرف', 'district' => 'بعبدا'],
            ['name' => 'راس المتن', 'district' => 'بعبدا'],
            ['name' => 'رويسة البلوط', 'district' => 'بعبدا'],
            ['name' => 'زندوقه', 'district' => 'بعبدا'],
            ['name' => 'سبنيه', 'district' => 'بعبدا'],
            ['name' => 'شويت', 'district' => 'بعبدا'],
            ['name' => 'صليما', 'district' => 'بعبدا'],
            ['name' => 'عاريا', 'district' => 'بعبدا'],
            ['name' => 'عين الرمانة', 'district' => 'بعبدا'],
            ['name' => 'عين موفق', 'district' => 'بعبدا'],
            ['name' => 'فالوغا', 'district' => 'بعبدا'],
            ['name' => 'قبيع', 'district' => 'بعبدا'],
            ['name' => 'قتاله', 'district' => 'بعبدا'],
            ['name' => 'قرطاضة', 'district' => 'بعبدا'],
            ['name' => 'قرنايل', 'district' => 'بعبدا'],
            ['name' => 'كفرسلوان', 'district' => 'بعبدا'],
            ['name' => 'كفرشيما', 'district' => 'بعبدا'],
            ['name' => 'وادي شحرور السفلى', 'district' => 'بعبدا'],
            ['name' => 'وادي شحرور العليا', 'district' => 'بعبدا'],
            ['name' => 'الباروك', 'district' => 'الشوف'],
            ['name' => 'البرجين', 'district' => 'الشوف'],
            ['name' => 'البطال', 'district' => 'الشوف'],
            ['name' => 'البيره', 'district' => 'الشوف'],
            ['name' => 'الجاهلية', 'district' => 'الشوف'],
            ['name' => 'الجليليه', 'district' => 'الشوف'],
            ['name' => 'الجميليه', 'district' => 'الشوف'],
            ['name' => 'الجيه', 'district' => 'الشوف'],
            ['name' => 'الخريبه', 'district' => 'الشوف'],
            ['name' => 'الدامور', 'district' => 'الشوف'],
            ['name' => 'الدبية', 'district' => 'الشوف'],
            ['name' => 'الرميله', 'district' => 'الشوف'],
            ['name' => 'الزعرورية', 'district' => 'الشوف'],
            ['name' => 'السعديات', 'district' => 'الشوف'],
            ['name' => 'السمقانية', 'district' => 'الشوف'],
            ['name' => 'الفريديس', 'district' => 'الشوف'],
            ['name' => 'الفواره', 'district' => 'الشوف'],
            ['name' => 'الكحلونية', 'district' => 'الشوف'],
            ['name' => 'الكنيسة', 'district' => 'الشوف'],
            ['name' => 'المحتقره دير المخلص', 'district' => 'الشوف'],
            ['name' => 'المختارة', 'district' => 'الشوف'],
            ['name' => 'المشرف', 'district' => 'الشوف'],
            ['name' => 'المطله', 'district' => 'الشوف'],
            ['name' => 'المعنيه', 'district' => 'الشوف'],
            ['name' => 'المغيريه', 'district' => 'الشوف'],
            ['name' => 'الناعمه', 'district' => 'الشوف'],
            ['name' => 'الوردانية', 'district' => 'الشوف'],
            ['name' => 'الورهانية', 'district' => 'الشوف'],
            ['name' => 'باتر', 'district' => 'الشوف'],
            ['name' => 'بتلون', 'district' => 'الشوف'],
            ['name' => 'برجا', 'district' => 'الشوف'],
            ['name' => 'بريح', 'district' => 'الشوف'],
            ['name' => 'بسابا', 'district' => 'الشوف'],
            ['name' => 'بشتفين', 'district' => 'الشوف'],
            ['name' => 'بطمه', 'district' => 'الشوف'],
            ['name' => 'بعاصير', 'district' => 'الشوف'],
            ['name' => 'بعذران', 'district' => 'الشوف'],
            ['name' => 'بعقلين التحتا', 'district' => 'الشوف'],
            ['name' => 'بعقلين الفوقا', 'district' => 'الشوف'],
            ['name' => 'بقعاتا', 'district' => 'الشوف'],
            ['name' => 'بكيفا', 'district' => 'الشوف'],
            ['name' => 'بنويتي', 'district' => 'الشوف'],
            ['name' => 'بيت الدين', 'district' => 'الشوف'],
            ['name' => 'بيقون', 'district' => 'الشوف'],
            ['name' => 'جباع', 'district' => 'الشوف'],
            ['name' => 'جدرا - وادي الزينة', 'district' => 'الشوف'],
            ['name' => 'جديدة الشوف', 'district' => 'الشوف'],
            ['name' => 'جون', 'district' => 'الشوف'],
            ['name' => 'حارة الناعمه', 'district' => 'الشوف'],
            ['name' => 'حارة بعاصير', 'district' => 'الشوف'],
            ['name' => 'حارة جندل', 'district' => 'الشوف'],
            ['name' => 'حصروت', 'district' => 'الشوف'],
            ['name' => 'خربة بسري', 'district' => 'الشوف'],
            ['name' => 'داريا', 'district' => 'الشوف'],
            ['name' => 'دلهون', 'district' => 'الشوف'],
            ['name' => 'دميت', 'district' => 'الشوف'],
            ['name' => 'دير القمر', 'district' => 'الشوف'],
            ['name' => 'دير بابا', 'district' => 'الشوف'],
            ['name' => 'دير دوريت', 'district' => 'الشوف'],
            ['name' => 'دير كوشه', 'district' => 'الشوف'],
            ['name' => 'سبلين', 'district' => 'الشوف'],
            ['name' => 'سرجبال', 'district' => 'الشوف'],
            ['name' => 'شحيم حي البدوي', 'district' => 'الشوف'],
            ['name' => 'شحيم حي البيادر', 'district' => 'الشوف'],
            ['name' => 'شحيم حي الجامع', 'district' => 'الشوف'],
            ['name' => 'شحيم حي السهله', 'district' => 'الشوف'],
            ['name' => 'شحيم حي الشريفة', 'district' => 'الشوف'],
            ['name' => 'شحيم حي الوسطاني', 'district' => 'الشوف'],
            ['name' => 'شحيم حي شحرور', 'district' => 'الشوف'],
            ['name' => 'شوريت', 'district' => 'الشوف'],
            ['name' => 'ضهر المغارة', 'district' => 'الشوف'],
            ['name' => 'عانوت', 'district' => 'الشوف'],
            ['name' => 'عترين', 'district' => 'الشوف'],
            ['name' => 'علمان', 'district' => 'الشوف'],
            ['name' => 'عماطور', 'district' => 'الشوف'],
            ['name' => 'عميق', 'district' => 'الشوف'],
            ['name' => 'عين الاسد والشميس', 'district' => 'الشوف'],
            ['name' => 'عين الحور', 'district' => 'الشوف'],
            ['name' => 'عين زحلتا', 'district' => 'الشوف'],
            ['name' => 'عين قني', 'district' => 'الشوف'],
            ['name' => 'عين وزين', 'district' => 'الشوف'],
            ['name' => 'عينبال', 'district' => 'الشوف'],
            ['name' => 'غريفه', 'district' => 'الشوف'],
            ['name' => 'كترمايا', 'district' => 'الشوف'],
            ['name' => 'كفر فاقود', 'district' => 'الشوف'],
            ['name' => 'كفر قطره', 'district' => 'الشوف'],
            ['name' => 'كفرحي', 'district' => 'الشوف'],
            ['name' => 'كفرحيم', 'district' => 'الشوف'],
            ['name' => 'كفرنبرخ', 'district' => 'الشوف'],
            ['name' => 'كفرنيس', 'district' => 'الشوف'],
            ['name' => 'كليليه', 'district' => 'الشوف'],
            ['name' => 'مجدل المعوش', 'district' => 'الشوف'],
            ['name' => 'مجدلونا', 'district' => 'الشوف'],
            ['name' => 'مرج برجا', 'district' => 'الشوف'],
            ['name' => 'مرستي', 'district' => 'الشوف'],
            ['name' => 'مزبود', 'district' => 'الشوف'],
            ['name' => 'مزرعة الشوف', 'district' => 'الشوف'],
            ['name' => 'مزرعة الضهر', 'district' => 'الشوف'],
            ['name' => 'مزموره', 'district' => 'الشوف'],
            ['name' => 'معاصر الشوف', 'district' => 'الشوف'],
            ['name' => 'معاصر بيت الدين', 'district' => 'الشوف'],
            ['name' => 'نيحا', 'district' => 'الشوف'],
            ['name' => 'وادي الدير', 'district' => 'الشوف'],
            ['name' => 'وادي الست', 'district' => 'الشوف'],
            ['name' => 'وادي بنحليه', 'district' => 'الشوف'],
            ['name' => 'وادي دير دوريت', 'district' => 'الشوف'],
            ['name' => 'اغميد', 'district' => 'عاليه'],
            ['name' => 'البساتين', 'district' => 'عاليه'],
            ['name' => 'البنيه', 'district' => 'عاليه'],
            ['name' => 'التعزانية', 'district' => 'عاليه'],
            ['name' => 'الرجمة', 'district' => 'عاليه'],
            ['name' => 'الرمليه', 'district' => 'عاليه'],
            ['name' => 'الشويفات حي الامراء', 'district' => 'عاليه'],
            ['name' => 'الشويفات حي العمروسية', 'district' => 'عاليه'],
            ['name' => 'الشويفات حي القبة', 'district' => 'عاليه'],
            ['name' => 'العزونية', 'district' => 'عاليه'],
            ['name' => 'الغابون', 'district' => 'عاليه'],
            ['name' => 'القماطية', 'district' => 'عاليه'],
            ['name' => 'الكحالة', 'district' => 'عاليه'],
            ['name' => 'المريجات', 'district' => 'عاليه'],
            ['name' => 'المشرفه', 'district' => 'عاليه'],
            ['name' => 'المنصوريه', 'district' => 'عاليه'],
            ['name' => 'بتاتر', 'district' => 'عاليه'],
            ['name' => 'بحمدون', 'district' => 'عاليه'],
            ['name' => 'بحواره', 'district' => 'عاليه'],
            ['name' => 'بخشتيه', 'district' => 'عاليه'],
            ['name' => 'بدادون', 'district' => 'عاليه'],
            ['name' => 'بدغان', 'district' => 'عاليه'],
            ['name' => 'بسرين', 'district' => 'عاليه'],
            ['name' => 'بسوس', 'district' => 'عاليه'],
            ['name' => 'بشامون', 'district' => 'عاليه'],
            ['name' => 'بطلون', 'district' => 'عاليه'],
            ['name' => 'بعورته', 'district' => 'عاليه'],
            ['name' => 'بليبل', 'district' => 'عاليه'],
            ['name' => 'بمكين', 'district' => 'عاليه'],
            ['name' => 'بمهريه', 'district' => 'عاليه'],
            ['name' => 'بوزريده', 'district' => 'عاليه'],
            ['name' => 'بيصور', 'district' => 'عاليه'],
            ['name' => 'جسر القاضي', 'district' => 'عاليه'],
            ['name' => 'حبرامون', 'district' => 'عاليه'],
            ['name' => 'حومال', 'district' => 'عاليه'],
            ['name' => 'دفون', 'district' => 'عاليه'],
            ['name' => 'دقون', 'district' => 'عاليه'],
            ['name' => 'دوير الرمان', 'district' => 'عاليه'],
            ['name' => 'دير قوبل', 'district' => 'عاليه'],
            ['name' => 'رشميا', 'district' => 'عاليه'],
            ['name' => 'رمحالا', 'district' => 'عاليه'],
            ['name' => 'رويسة النعمان', 'district' => 'عاليه'],
            ['name' => 'سرحمول', 'district' => 'عاليه'],
            ['name' => 'سلفايا', 'district' => 'عاليه'],
            ['name' => 'سوق الغرب', 'district' => 'عاليه'],
            ['name' => 'شارون', 'district' => 'عاليه'],
            ['name' => 'شانيه', 'district' => 'عاليه'],
            ['name' => 'شرتون', 'district' => 'عاليه'],
            ['name' => 'شملان', 'district' => 'عاليه'],
            ['name' => 'صوفر', 'district' => 'عاليه'],
            ['name' => 'عاليه شمالي', 'district' => 'عاليه'],
            ['name' => 'عاليه غربي', 'district' => 'عاليه'],
            ['name' => 'عاليه قبلي', 'district' => 'عاليه'],
            ['name' => 'عاليه وسطاني', 'district' => 'عاليه'],
            ['name' => 'عبيه', 'district' => 'عاليه'],
            ['name' => 'عرمون', 'district' => 'عاليه'],
            ['name' => 'عيتات', 'district' => 'عاليه'],
            ['name' => 'عين الجديدة', 'district' => 'عاليه'],
            ['name' => 'عين الحلزون', 'district' => 'عاليه'],
            ['name' => 'عين الرمانة', 'district' => 'عاليه'],
            ['name' => 'عين السيدة', 'district' => 'عاليه'],
            ['name' => 'عين الفريديس', 'district' => 'عاليه'],
            ['name' => 'عين المرج', 'district' => 'عاليه'],
            ['name' => 'عين تراز', 'district' => 'عاليه'],
            ['name' => 'عين داره', 'district' => 'عاليه'],
            ['name' => 'عين درافيل', 'district' => 'عاليه'],
            ['name' => 'عين عنوب', 'district' => 'عاليه'],
            ['name' => 'عين كسور', 'district' => 'عاليه'],
            ['name' => 'عيناب', 'district' => 'عاليه'],
            ['name' => 'كفر عميه', 'district' => 'عاليه'],
            ['name' => 'كفرمتى', 'district' => 'عاليه'],
            ['name' => 'كيفون', 'district' => 'عاليه'],
            ['name' => 'مجدل بعنا', 'district' => 'عاليه'],
            ['name' => 'مجدليا', 'district' => 'عاليه'],
            ['name' => 'محطة بحمدون', 'district' => 'عاليه'],
            ['name' => 'مزرعة النهر', 'district' => 'عاليه'],
            ['name' => 'معصريتي', 'district' => 'عاليه'],
        ];

        foreach ($towns as $townData) {
            $district = District::where('name', $townData['district'])->first();
            if ($district) {
                $townName = $townData['name'];

                // Add district name in parentheses for duplicate towns
                if (in_array($townName, $duplicateTowns)) {
                    $townName = $townName.' ('.$townData['district'].')';
                }

                Town::create([
                    'name' => $townName,
                    'district_id' => $district->id,
                ]);
            }
        }
        $this->command->info('Successfully seeded towns!');
    }
}
